In [2]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [3]:
steps = [("standard scaler",StandardScaler()),
         ("classifier",LogisticRegression())]

In [4]:
steps

[('standard scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [6]:
pipe = Pipeline(steps)

In [7]:
pipe

Pipeline(steps=[('standard scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

for visualizing the pipeline we use set_config


In [8]:
from sklearn import set_config

In [9]:
set_config(display="diagram")

CREATING THE DATA SET

In [11]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000)

In [12]:
X.shape

(1000, 20)

In [13]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=33 ,random_state=42)

In [14]:
X_train

array([[ 0.02733079, -1.04967463,  0.04386258, ..., -1.19260775,
        -2.25287191,  0.99697034],
       [-0.13327824,  1.21687098,  0.77635277, ..., -1.03276932,
        -2.04548324,  0.74335865],
       [-0.82623834, -1.04302065,  1.28520745, ...,  0.93335349,
         0.74702656,  0.48516536],
       ...,
       [ 0.52716185,  0.67930167, -1.109565  , ..., -0.0844666 ,
        -0.56219048, -0.17707238],
       [-0.56529684, -0.97539062, -0.83532177, ...,  0.82422378,
         0.35957884, -0.63317316],
       [ 1.32212441, -0.38872426, -1.17495163, ..., -2.03597626,
        -1.98630656, -1.89394711]])

In [15]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [16]:
y_pred =pipe.predict(X_test)

In [17]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

example 2:

Displaying a pipeline with standard scaler ,dimensionality reduction and then estimator

In [18]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [27]:
steps2 = [("scaling",StandardScaler()),
          ("decomposition",PCA(n_components=3)),
           ("classifier2",SVC())]

In [28]:
steps2

[('scaling', StandardScaler()),
 ('decomposition', PCA(n_components=3)),
 ('classifier2', SVC())]

In [29]:
pipe2 = Pipeline(steps2)

In [30]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()),
                ('decomposition', PCA(n_components=3)),
                ('classifier2', SVC())])

In [31]:
y_pred2=pipe2.predict(X_test)

In [32]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

COMPLEX EXAMPLE of column transform

In [33]:
from sklearn.impute import SimpleImputer
import numpy as np

Numeric processing pipeline

In [34]:
numeric_processor = Pipeline(steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy = "mean")),
                                    ("scaling",StandardScaler())])

In [35]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaling', StandardScaler())])

Categorical Processing Pipeline

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
category_processor = Pipeline(steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy = "constant")),
                                    ("Onehot encoding",OneHotEncoder(handle_unknown="ignore"))])

In [41]:
category_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('Onehot encoding', OneHotEncoder(handle_unknown='ignore'))])

inorder to combine both the pipelines we need to import ColumnTransform from sklearn.compse

In [43]:
## Combining the processing techniques
from sklearn.compose import ColumnTransformer

In [46]:
preprocessor = ColumnTransformer([("categorical",category_processor,["gender","city"]),
                                 ("numerical",numeric_processor,["age","height"])])

In [47]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('Onehot encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['age', 'height'])])

In [48]:
from sklearn.pipeline import make_pipeline

In [49]:
final_pipe = make_pipeline(preprocessor,LogisticRegression())

In [50]:
final_pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('Onehot '
                                                                   'encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])